# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

shallow_clone: true

init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2017

environment:
  nodejs_version: "4.2"
  PLATFORM: windows-10-store
  matrix:
    - PLUGIN: cordova-plugin-battery-status
    - PLUGIN: cordova-plugin-camera
    - PLUGIN: cordova-plugin-console
    - PLUGIN: cordova-plugin-contacts
    - PLUGIN: cordova-plugin-device
    - PLUGIN: cordova-plugin-device-motion
    - PLUGIN: cordova-plugin-device-orientation
    - PLUGIN: cordova-plugin-dialogs
    - PLUGIN: cordova-plugin-file
    - PLUGIN: cordova-plugin-file-transfer
    - PLUGIN: cordova-plugin-geolocation
    - PLUGIN: cordova-plugin-globalization
    - PLUGIN: cordova-plugin-inappbrowser
    - PLUGIN: cordova-plugin-media
    - PLUGIN: cordova-plugin-media-capture
    - PLUGIN: cordova-plugin-network-information
    - PLUGIN: cordova-plugin-screen-orientation
    - PLUGIN: cordova-plugin-splashscreen
    - PLUGIN: cordova-plugin-statusbar
    - PLUGIN: cordova-plugin-vibration

install:
  - npm cache clean -f
  - node --version
  - npm install -g cordova-paramedic@https://github.com/apache/cordova-paramedic.git
  - git clone --depth=1 --branch=master https://github.com/apache/%PLUGIN%
  - git clone --depth=1 --branch=master https://github.com/apache/cordova-coho
  - cd cordova-coho\src && npm install && cd ..
  # installing dev cordova
  - cordova-coho\coho repo-clone -r tools
  - cordova-coho\coho npm-link
  - cd cordova-cli && npm install && cd ..
  - cordova-cli\bin\cordova -v

build: off

test_script:
  - set CLI_ARG="--cli cordova-cli\bin\cordova"
  - cordova-paramedic --config periodic\%PLATFORM% --plugin %cd%\%PLUGIN% --justBuild %CLI_ARG%
